name: push
on:
  push:
    tags:
      - 'uat-*'
    branches:
      - main

env:
  BRANCH: main

jobs:
   build:
     runs-on: ubuntu-latest
     steps:

     - uses: actions/checkout@v3
       with:
         fetch-depth: 0

     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
        echo "$GITHUB_CONTEXT"
        env | sort

     - name: Get Tag
       if: startsWith(github.ref, 'refs/tags')
       id: get_tag
       run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}

     - name: Test get tag
       if: startsWith(github.ref, 'refs/tags')
       run: |
        echo "${{ steps.get_tag.outputs.TAG_NAME }}"
        echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"

     - name: Is tag on the branch
#       if: startsWith(github.ref, 'refs/tags')
       run: |
         git branch -a
         git log "refs/heads/${BRANCH}"
         echo
         git log "refs/heads/${BRANCH}" -1
         echo
         git log "refs/heads/${BRANCH}" -1 --pretty='%D' ${GITHUB_REF_NAME}
         echo
         git log "refs/heads/${BRANCH}" -1 --pretty='%D' ${GITHUB_REF_NAME} &>/dev/null \
           && echo "tag ${GITHUB_REF_NAME} is on the branch ${BRANCH}" \
           || echo "tag ${GITHUB_REF_NAME} is not on the branch ${BRANCH}"
