name: Test pull request closed

on:
  pull_request:
    types: [closed]
    branches:
    - main

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
        echo "$GITHUB_CONTEXT"
        echo
        env | sort
