name: push
on:
  push:
    tags:
      - 'uat-*'
    branches:
      - main
jobs:
   build:
#     if: github.event.base_ref == 'refs/heads/master'
     runs-on: ubuntu-latest
     steps:
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
        echo "$GITHUB_CONTEXT"
        env | sort
        echo "end"
