name: STAGING - Build and deploy

on:
  workflow_dispatch:

  push:
    branches:
      - RELEASE-*

  # push from github action do not trigger workflow to avoid infinie loop
  workflow_run:
    workflows: [ "Bump version" ]
    types:
      - completed

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
        echo "$GITHUB_CONTEXT"
        echo
        env | sort

     - name: 'test get artifacts'
       run: |
         set -x
         CURRENT_BRANCH_ARTIFACT_URL=$(gh api \
           -H "Accept: application/vnd.github.v3+json" \
           "${WORKFLOW_RUN_ARTIFACTS_URL##https://api.github.com/}" \
           | jq '.artifacts[0].archive_download_url')
         
         echo "CURRENT_BRANCH_ARTIFACT_URL: ${CURRENT_BRANCH_ARTIFACT_URL}"
         
         gh api \
           -H "Accept: application/vnd.github.v3+json" \
           "${$CURRENT_BRANCH_ARTIFACT_URL##https://api.github.com/}" \
           > release_branch.zip
         
         unzip release_branch.zip
         RELEASE_BRANCH=$(cat CREATED_BRANCH.txt)
         
         echo "::set-output name=releaseBranch::${RELEASE_BRANCH}"
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         WORKFLOW_RUN_ARTIFACTS_URL: ${{ github.event.workflow_run.artifacts_url }}
