name: Test pull request closed

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo
          env | sort

      - name: Get Branch Name
        id: branch_name
        uses: tj-actions/branch-names@v5.2

      - name: test variables
        run: |
          echo "tj-actions/branch-names ${{ steps.branch_name.outputs.current_branch }}"
          echo
          echo "GITHUB_HEAD_REF ${GITHUB_HEAD_REF}"
          echo ":github.head_ref: ${{ github.head_ref }}"
          echo
          echo "GITHUB_BASE_REF ${GITHUB_BASE_REF}"
          echo ":github.base_ref: ${{ github.base_ref }}"
